package entity;
// Generated 09-may-2017 16:28:46 by Hibernate Tools 4.3.1



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String idUsers;
     private String name;
     private String password;
     private String type;

    public Users() {
    }

    public Users(String idUsers, String name, String password, String type) {
       this.idUsers = idUsers;
       this.name = name;
       this.password = password;
       this.type = type;
    }
   
    public String getIdUsers() {
        return this.idUsers;
    }
    
    public void setIdUsers(String idUsers) {
        this.idUsers = idUsers;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


